name: TransferItems
version: 1.0
main: theandrey.transferitems.TransferItemsPlugin
author: TheAndrey
commands:
    putitems:
        permission: transferitems.put
    getitems:
        permission: transferitems.get